### ISSUE TITLE
Mistake in version listing?

### ISSUE THREAD

**Issue by nanaba12** [leoetlino/project-restoration-site#2]
I think there is a mistake on this part of the site:
![image](https://user-images.githubusercontent.com/97263190/168326592-13d687ce-d640-4f5b-8862-6d938cd43018.png)

Only one should be v100, and the other one should be v101, right?

**Comment by leoetlino** [comment]
Nope, because optional updates appear to be ignored under certain circumstances, so the patch gets applied to the base executable (v100) and not to the updated executable (v101).

Or at least that's what I _think_ is happening because some users reported that v100 works for them even though they have an updated eShop or 1.0 gamecard version of the game. It's kinda weird but the current set of instructions is what ended up working for most users.
